
export const Data = [
    {id:1,
    name:"aglaonema plant",
    category_type:"indoor",
    type:"organic",
    price:45,
    qty:1,
    quantity:20,
    qty_sold:120,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/aglaonema_plant.png",
    product_thumb:"./products/aglaonema_plant_thumb.png",
    isdiscount: false,
    discount:0,
},
 {id:2,
    name:"aglaonema plant",
    category_type:"indoor",
    type:"organic",
    price:55,
    qty:1,
    quantity:30,
    qty_sold:90,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/aglaonema.png",
    product_thumb:"./products/aglaonema_thumb.png",
    isdiscount: false,
    discount:0,
},
 {id:3,
    name:"monstera plant",
    category_type:"indoor",
    type:"organic",
    price:25,
    qty:1,
    quantity:30,
    qty_sold:44,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/big_leaf_monstera.png",
    product_thumb:"./products/big_leaf_monstera_thumb.png",
    isdiscount: true,
    discount:23,
},
 {id:4,
    name:"aglaonema plant",
    category_type:"indoor",
    type:"organic",
    price:55,
    qty:1,
    quantity:30,
    qty_sold:54,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/bigleafaglaonema.png",
    product_thumb:"./products/bigleafaglaonema_thumb.png",
    isdiscount: true,
    discount:12,
},
 {id:5,
    name:"cactus plant",
    category_type:"indoor",
    type:"organic",
    price:55,
    qty:1,
    quantity:30,
    qty_sold:54,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/cactusleafplant.png",
    product_thumb:"./products/cactusleafplant_thumb.png",
    isdiscount: false,
    discount:0,
},
 {id:6,
    name:"corn plant",
    category_type:"indoor",
    type:"organic",
    price:43,
    qty:1,
    quantity:30,
    qty_sold:8,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/cornplant.png",
    product_thumb:"./products/cornplant_thumb.png",
    isdiscount: true,
    discount:30,
},
{id:7,
    name:"guava leaf plant",
    category_type:"indoor",
    type:"organic",
    price:60,
    qty:1,
    quantity:30,
    qty_sold:8,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/guavaleaf.png",
    product_thumb:"./products/guavaleaf_thumb.png",
    isdiscount: true,
    discount:25,
},
{id:8,
    name:"heart leaf philodendron plant",
    category_type:"indoor",
    type:"organic",
    price:99,
    qty:1,
    quantity:30,
    qty_sold:67,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/heartleaf_philodendron.png",
    product_thumb:"./products/heartleaf_philodendron_thumb.png",
    isdiscount: false,
    discount:0,
},
{id:9,
    name:"monstera plant",
    category_type:"indoor",
    type:"organic",
    price:99,
    qty:1,
    quantity:30,
    qty_sold:67,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/monstera1.png",
    product_thumb:"./products/monstera1_thumb.png",
    isdiscount: false,
    discount:0,
},
{id:10,
    name:"monstera plant",
    category_type:"indoor",
    type:"organic",
    price:52,
    qty:1,
    quantity:30,
    qty_sold:67,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/monstera2.png",
    product_thumb:"./products/monstera2_thumb.png",
    isdiscount: false,
    discount:0,
},
{id:11,
    name:"pearleaf plant",
    category_type:"indoor",
    type:"organic",
    price:42,
    qty:1,
    quantity:30,
    qty_sold:27,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/pearleafplant.png",
    product_thumb:"./products/pearleafplant_thumb.png",
    isdiscount: true,
    discount:15,
},
{id:12,
    name:"philodendron plant",
    category_type:"indoor",
    type:"organic",
    price:32,
    qty:1,
    quantity:30,
    qty_sold:27,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/philodendron.png",
    product_thumb:"./products/philodendron_thumb.png",
    isdiscount: true,
    discount:15,
},

{id:13,
    name:"snake plant",
    category_type:"indoor",
    type:"organic",
    price:33,
    qty:1,
    quantity:30,
    qty_sold:27,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/short_snake_plant.png",
    product_thumb:"./products/short_snake_plant_thumb.png",
    isdiscount: true,
    discount:25,
},
{id:14,
    name:"snake plant",
    category_type:"indoor",
    type:"organic",
    price:39,
    qty:1,
    quantity:30,
    qty_sold:37,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/snakeplant.png",
    product_thumb:"./products/snakeplant_thumb.png",
    isdiscount: true,
    discount:15,
},
{id:15,
    name:"snake plant",
    category_type:"indoor",
    type:"organic",
    price:59,
    qty:1,
    quantity:30,
    qty_sold:87,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/snakeplant2.png",
    product_thumb:"./products/snakeplant2_thumb.png",
    isdiscount: false,
    discount:0,
},
{id:16,
    name:"white flower plant",
    category_type:"indoor",
    type:"organic",
    price:59,
    qty:1,
    quantity:30,
    qty_sold:87,
    overview:"Few description about the plant and more other description concerning the plant, the list of what the plant has and what it does not have will be listed below for proper reference and more lorem ipsum txt content to describe the product fully",
    features:["product has feature1","product has feature2", "product has feature3", "product has feature4", "product has feature5"],
    isliked:false,
    product_image:"./products/white_flower.png",
    product_thumb:"./products/white_flower_thumb.png",
    isdiscount: false,
    discount:0,
},
]