export const Foot_list = [
    {id:1,
    name:"Help center",
    link:"help",
},
{id:2,
    name:"How to shop on Deekor",
    link:"shopping guild",
},
{id:3,
    name:"Report a product",
    link:"report",
},
{id:4,
    name:"How to return a product on Deekor",
    link:"return policy",
},
{id:5,
    name:"Delivery options and timelines",
    link:"delivery options",
},
]